[tool.poetry]
name = "py-wave-runup"
version = "0.1.4"
description = "Empirical wave runup models implemented in Python"
authors = ["Chris Leaman"]
license = "GPL-3.0+"
readme = 'README.rst'
repository = 'https://github.com/chrisleaman/py-wave-runup'
homepage = 'https://github.com/chrisleaman/py-wave-runup'
documentation = 'https://py-wave-runup.readthedocs.io'

[tool.poetry.dependencies]
python = "^3.5 || ^3.6 || ^3.7"
numpy = "^1.16"

[tool.poetry.dev-dependencies]
tox = "^3.8"
coverage = "^4.5"
pytest-runner = "^4.4"
pytest = "^4.4"
pre-commit = "^1.16"
codecov = "^2.0"
pytest-cov = "^2.6"
sphinx = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
